apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e33p2o02n-java-springboot
  janus-idp.io/tekton: e33p2o02n-java-springboot
  backstage.io/kubernetes-id: e33p2o02n-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: e33p2o02n-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
